spring:
  datasource:
    url: jdbc:mysql://mysql:3306/your_database_name?useSSL=false&serverTimezone=UTC
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # 로깅 설정
  logging:
    level:
      org:
        hibernate: DEBUG

